# Generated by Django 5.1.4 on 2025-02-11 08:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Products',
            fields=[
                ('product_ID', models.AutoField(primary_key=True, serialize=False, verbose_name='Product ID')),
                ('product_Name', models.CharField(max_length=80, verbose_name='Product Name')),
                ('product_Description', models.CharField(max_length=200, verbose_name='Product Description')),
                ('product_Category', models.CharField(max_length=100, verbose_name='Product Category')),
                ('price', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Price')),
            ],
        ),
    ]
